# Reference: https://cloud.google.com/solutions/continuous-delivery-with-travis-ci
language: python
# Cache our Google Cloud SDK between commands
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
env:
# Make sure gcloud command is on our PATH
- PATH=$PATH:${HOME}/google-cloud-sdk/bin
before_install:
# Decrypt the credentials we added to the repo using the key we added with the Travis command line tool
- openssl aes-256-cbc -K $encrypted_997e293d8fa5_key -iv $encrypted_997e293d8fa5_iv -in client-secret.json.enc -out client-secret.json -d
install:
# If the Google Cloud SDK is not already cached, download it and unpack it
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- gcloud version
- gcloud auth activate-service-account --key-file client-secret.json
- gcloud config set project chesshacker-project
script:
- gcloud deployment-manager deployments update deployment --config=deployment.yml --preview
- gcloud deployment-manager deployments update deployment
