#!/usr/bin/env bash

cd "$( dirname "${BASH_SOURCE[0]}" )/.."
if [ -f super-secret-password.txt ]; then
  super_secret_password=$(cat super-secret-password.txt)
fi
if [ -z ${super_secret_password+x} ]; then
  echo "encrypt failed: super_secret_password was not provided"
  exit 1
fi
tar czf secure.tar.gz secure
openssl aes-256-cbc -k "${super_secret_password}" -in secure.tar.gz -out secure.tar.gz.enc
rm secure.tar.gz
